#version: '3.8'
services:
  mysqldb:
    platform: linux/amd64
    image: mysql:8.0.36
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassWd
      - MYSQL_USER="sample"
      - MYSQL_PASSWORD="samplePassWd"
      - MYSQL_DATABASE="sampleDB"
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQLDB_USER}", "-p${MYSQLDB_PASSWORD}"]
      interval: 30s
      timeout: 30s
      retries: 3